baseURL = 'https://ewerlopes.github.io/'
languageCode = 'en-us'
theme = 'mytheme'
title = 'Half-bayesianism'

# Navigation
[languages]
    [languages.en]
        contentDir = 'content/en'
        languageCode = 'en'
        languageName = 'English'
        weight = 10
        [languages.en.menu]
            [[languages.en.menu.main]]
                name = "posts"
                url = "/posts/"
                weight = 4

            [[languages.en.menu.main]]
                name = "about"
                url = "/about/index.html"
                weight = 3

            [[languages.en.menu.main]]
                name = "tags"
                url = "/tags/"
                weight = 2
            [[languages.en.menu.main]]
                name = "categories"
                url = "/categories/"
                weight = 1

    [languages.pt]
        contentDir = 'content/pt'
        languageCode = 'pt'
        languageName = 'Portuguese'
        weight = 20
        [languages.pt.menu]
            [[languages.pt.menu.main]]
                name = "posts"
                url = "/posts/"
                weight = 4

            [[languages.pt.menu.main]]
                name = "sobre"
                url = "/about/"
                weight = 3

            [[languages.pt.menu.main]]
                name = "tags"
                url = "/tags/"
                weight = 2
            [[languages.pt.menu.main]]
                name = "categorias"
                url = "/categories/"
                weight = 1